packages:
  - apps/*
  - packages/*

catalog:
  "@libsql/client": ^0.17.0
  "@types/node": 24.10.4
  typescript: ^5.9.3
  zod: ^4.3.6

catalogs:
  better-auth:
    better-auth: ^1.4.19
  cloudflare:
    "@cloudflare/vite-plugin": ^1.25.4
    "@cloudflare/workers-types": ^4.20260303.0
    wrangler: ^4.68.0
  dicebear:
    "@dicebear/collection": ^9.3.2
    "@dicebear/core": ^9.3.2
  drizzle:
    drizzle-kit: ^0.31.9
    drizzle-orm: ^0.45.1
  react:
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwind:
    "@tailwindcss/vite": ^4.2.1
    tailwind-merge: ^3.5.0
    tailwindcss: ^4.2.1
    tw-animate-css: ^1.4.0
  tanstack:
    "@tanstack/react-form": ^1.28.3
    "@tanstack/react-router": ^1.162.8
    "@tanstack/react-start": ^1.162.8
    "@tanstack/react-table": ^8.21.3
  hono:
    hono: ^4.12.2
    "@hono/zod-validator": ^0.7.6
  vite:
    "@vitejs/plugin-react": ^5.1.4
    "@vitest/browser-playwright": ^4.0.18
    vite: ^7.3.1
    vitest: ^4.0.18
    vitest-browser-react: ^2.0.5
